### ISSUE TITLE
可以帮忙更新到AHK版本吗？

### ISSUE THREAD

**Issue by zpc1042245970** [Hirotonx/Apex-Legends-Shake-Reducing_Recoil#1]
能量枪基本都压不住 高倍镜表现也不佳 感谢

**Comment by Hozira** [comment]
AHK容易被ban，AHK还不如直接用https://github.com/mgsweet/Apex-NoRecoil-2021 (有一定的风险)
压不住基本上是灵敏度的问题修改https://github.com/Hirotonx/Apex-Legends-Shake-Reducing_Recoil/blob/1ad6230e87ecca08ecf7900edc65864d306a2ac9/main.py#L5          把数字调大点就可以了

**Comment by zpc1042245970** [comment]
> AHK容易被ban，AHK还不如直接用https://github.com/mgsweet/Apex-NoRecoil-2021 (有一定的风险) 压不住基本上是灵敏度的问题修改
> 
> https://github.com/Hirotonx/Apex-Legends-Shake-Reducing_Recoil/blob/1ad6230e87ecca08ecf7900edc65864d306a2ac9/main.py#L5
> 
> 把数字调大点就可以了

python的不会用，请问支持2k分辨率吗，想加个QQ学习一下如何使用

**Comment by Hirotonx** [comment]
> 

277229354
